### ISSUE TITLE
Peer To peer code review

### ISSUE THREAD

**Issue by Chimoneg27** [egichuhis/tv-shows-capstone#28]
### Required Changes ♻️

✅Nice color scheme
✅Nice header and footer feature
✅Descriptive PR

- Please add a function that generates your cards, as this is line with project requirements🙏
- Also improve your README file, this makes it easier for other to have a brief introduction to your project🙏

**Comment by egichuhis** [comment]
Thanks, @Chimoneg27, the Cards are WIP, but thanks for the reminder.
